server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:aa12321.@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

xc-service-manage-media:
  video-location: D:/FFmpeg/XcProject-video/ # ps location 必须最后一/结尾
  ffmpeg-path: D:/FFmpeg/ffmpeg-20180227-fa0c9d6-win64-static/bin/ffmpeg.exe
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
