server:
  port: 44000
spring:
  application:
    name: test-rabbitmq-consumer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: / # 虚拟机路径,不同虚拟机代表不同的RabbitMQ服务器
