server:
  port: ${PORT:31100 }
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri:  mongodb://root:aa12321.@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: ${QUEUE:queue_cms_postpage_01}
    routingKey: ${ROUTINGKEY:5a751fab6abb5044e0d19ea1}	#此routingKey为门户站点ID

# 一个Queue对应一个站点,一个Queue可以被多台服务器(内容相同)监听 --> nginx 做负载均衡